mkdir build -p
cd build
cmake .. -DCUB_ENABLE_HEADER_TESTING=OFF -DCUB_ENABLE_TESTING=OFF -DCUB_ENABLE_EXAMPLES=ON -DTHRUST_ENABLE_HEADER_TESTING=OFF -DTHRUST_INCLUDE_CUB_CMAKE=ON  -DTHRUST_AUTO_DETECT_COMPUTE_ARCHS=ON -G Ninja
ninja cub.all.example.device.radix_sort
